### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by TheBiblMan** [TheBiblMan/redeob-rs#5]
On large methods, the condense method in the sorter impl takes up to 10 minutes on some methods (ca. 13000 instructions). 70-80% of the program is the collectPredecessors method.

**Comment by Polish-Civil** [comment]
Y u no jgrapht tho?

**Comment by TheBiblMan** [comment]
too much extra shit in it that i dont need

**Comment by Polish-Civil** [comment]
lol.., then remove 80% of java rt too

**Comment by TheBiblMan** [comment]
i was planning to do that.

**Comment by TheBiblMan** [comment]
Rewrote the graph impl(https://github.com/TheBiblMan/redeob-rs/commit/4afb927f6a9b55c8ca37848d70e3ab16e77ec46b) along with amending the cfg implementation, in particular the collectPredecessors method in GraphUtils.(https://github.com/TheBiblMan/redeob-rs/commit/f27a53e1b4c0f6dfa815e0abae46f59ff3ba8e51) 
This fixed the performance problem dramatically. 

P.S. It seemed like the profiler I was using was slowing the program down A LOT (callbacks being instrumented in) which may have skewed the results a little bit, but the program was still very slow before this patch.
